<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.306">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Parcial 3 Santiago Uribe</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="parcial3_files/libs/clipboard/clipboard.min.js"></script>
<script src="parcial3_files/libs/quarto-html/quarto.js"></script>
<script src="parcial3_files/libs/quarto-html/popper.min.js"></script>
<script src="parcial3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="parcial3_files/libs/quarto-html/anchor.min.js"></script>
<link href="parcial3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="parcial3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="parcial3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="parcial3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="parcial3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Parcial 3 Santiago Uribe</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'auto.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dim_df <span class="op">=</span> df.shape</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The dataset consists of </span><span class="sc">{</span>dim_df[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> rows and </span><span class="sc">{</span>dim_df[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> columns"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The dataset consists of 392 rows and 9 columns</code></pre>
</div>
</div>
<p>Let’s check how much missing data there is by columns</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Missing values by column</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="61">
<pre><code>mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
year            0
origin          0
name            0
dtype: int64</code></pre>
</div>
</div>
<section id="descriptive-statistics" class="level1">
<h1>Descriptive Statistics</h1>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="62">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mpg</th>
<th data-quarto-table-cell-role="th">cylinders</th>
<th data-quarto-table-cell-role="th">displacement</th>
<th data-quarto-table-cell-role="th">horsepower</th>
<th data-quarto-table-cell-role="th">weight</th>
<th data-quarto-table-cell-role="th">acceleration</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">origin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>392.000000</td>
<td>392.000000</td>
<td>392.000000</td>
<td>392.000000</td>
<td>392.000000</td>
<td>392.000000</td>
<td>392.000000</td>
<td>392.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>23.445918</td>
<td>5.471939</td>
<td>194.411990</td>
<td>104.469388</td>
<td>2977.584184</td>
<td>15.541327</td>
<td>75.979592</td>
<td>1.576531</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>7.805007</td>
<td>1.705783</td>
<td>104.644004</td>
<td>38.491160</td>
<td>849.402560</td>
<td>2.758864</td>
<td>3.683737</td>
<td>0.805518</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>9.000000</td>
<td>3.000000</td>
<td>68.000000</td>
<td>46.000000</td>
<td>1613.000000</td>
<td>8.000000</td>
<td>70.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>17.000000</td>
<td>4.000000</td>
<td>105.000000</td>
<td>75.000000</td>
<td>2225.250000</td>
<td>13.775000</td>
<td>73.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>22.750000</td>
<td>4.000000</td>
<td>151.000000</td>
<td>93.500000</td>
<td>2803.500000</td>
<td>15.500000</td>
<td>76.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>29.000000</td>
<td>8.000000</td>
<td>275.750000</td>
<td>126.000000</td>
<td>3614.750000</td>
<td>17.025000</td>
<td>79.000000</td>
<td>2.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>46.600000</td>
<td>8.000000</td>
<td>455.000000</td>
<td>230.000000</td>
<td>5140.000000</td>
<td>24.800000</td>
<td>82.000000</td>
<td>3.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Separate attributes by type</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>int_attributes <span class="op">=</span> df.select_dtypes(include<span class="op">=</span>[<span class="st">'int'</span>]).columns.to_list()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>float_attributes <span class="op">=</span> df.select_dtypes(include<span class="op">=</span>[<span class="st">'float'</span>]).columns.to_list()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>int_attributes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="64">
<pre><code>['cylinders', 'horsepower', 'weight', 'year', 'origin']</code></pre>
</div>
</div>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>float_attributes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="65">
<pre><code>['mpg', 'displacement', 'acceleration']</code></pre>
</div>
</div>
<p>With this we can see that the variables ‘cylinders’, ‘horsepower’, ‘weight’, ‘year’, ‘origin’ are discrete and the variables ‘mpg’, ‘displacement’, ‘acceleration’ are continuous.</p>
<section id="histograms-and-bar-diagrams" class="level3">
<h3 class="anchored" data-anchor-id="histograms-and-bar-diagrams">Histograms and Bar Diagrams</h3>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">6</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>axs <span class="op">=</span> axs[:<span class="dv">8</span>].ravel()</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, column <span class="kw">in</span> <span class="bu">enumerate</span>(df.columns):</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    column_data <span class="op">=</span> df[column]</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    column_type <span class="op">=</span> column_data.dtype</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> column_type <span class="op">==</span> <span class="st">'int64'</span>:  <span class="co"># Variables discretas</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>        sns.countplot(data<span class="op">=</span>df, x<span class="op">=</span>column, ax<span class="op">=</span>axs[i])</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> column <span class="kw">in</span> [<span class="st">'horsepower'</span>, <span class="st">'weight'</span>]:</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> column <span class="op">==</span> <span class="st">'horsepower'</span>: axs[i].set_xticks(axs[i].get_xticks()[::<span class="dv">10</span>])</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>: axs[i].set_xticks(axs[i].get_xticks()[::<span class="dv">20</span>])</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>            axs[i].tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">90</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> column_type <span class="op">==</span> <span class="st">'float64'</span>:  <span class="co"># Variables continuas</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>        sns.histplot(data<span class="op">=</span>df, x<span class="op">=</span>column, kde<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>axs[i])</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-9-output-1.png" width="1142" height="566"></p>
</div>
</div>
</section>
<section id="boxplots" class="level3">
<h3 class="anchored" data-anchor-id="boxplots">Boxplots</h3>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>numeric_attributes <span class="op">=</span> df.select_dtypes(include<span class="op">=</span>[<span class="st">'float'</span>, <span class="st">'int'</span>]).columns.to_list()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patches <span class="im">as</span> mpatches</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>fliers <span class="op">=</span> <span class="bu">dict</span>(markerfacecolor<span class="op">=</span><span class="st">'m'</span>, marker<span class="op">=</span><span class="st">'D'</span>) <span class="co">#atypical data</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>mean_ <span class="op">=</span> <span class="bu">dict</span>(markerfacecolor<span class="op">=</span><span class="st">'green'</span>, marker<span class="op">=</span><span class="st">'D'</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>mean_artist <span class="op">=</span> mpatches.Patch(facecolor<span class="op">=</span><span class="st">'green'</span>, label<span class="op">=</span><span class="st">'Mean'</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>ad_artist <span class="op">=</span> mpatches.Patch(color<span class="op">=</span><span class="st">'m'</span>, label<span class="op">=</span><span class="st">'Atypical Data'</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">12</span>,<span class="dv">6</span>))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>axs <span class="op">=</span> axs[:<span class="dv">8</span>].ravel()</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, col <span class="kw">in</span> <span class="bu">enumerate</span>(numeric_attributes):</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  bp <span class="op">=</span> axs[i].boxplot(df[col], vert<span class="op">=</span><span class="va">False</span>, flierprops<span class="op">=</span>fliers, showmeans<span class="op">=</span><span class="va">True</span>, meanprops<span class="op">=</span>mean_)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  axs[i].legend(handles<span class="op">=</span>[mean_artist, ad_artist], loc<span class="op">=</span><span class="st">'upper left'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  axs[i].set_title(col)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-11-output-1.png" width="1142" height="566"></p>
</div>
</div>
<p>The descriptive analysis performed reveals some interesting characteristics of the variables under study. It is observed that the variable “mpg” (miles per gallon) and “displacement” (engine displacement) show a rightward skewness in their distributions. This implies that there is a concentration of lower values at the left end of the distributions and a long tail towards higher values. On the other hand, the variable “acceleration” shows a distribution that could be considered centered, since the median and mean are approximately equal. In addition, the width of the box in the box plot indicates a low interquartile range.</p>
<p>For the variables “cylinders” (number of cylinders) and “origin” (origin of the car), it is observed that no whiskers are shown in the box plot. This indicates that the maximum value is equal to the third quartile and the minimum value is equal to the first quartile, respectively. In other words, there are no outliers in these variables and the distribution is completely contained within the box. You can see that most of the cars are American.</p>
<p>In the case of the variable “weight” (vehicle weight), there is a wide range of weights, with an almost uniform distribution. The absolute frequency shows that there are several different weights without repeating with a maximum frequency of 3.</p>
<p>Finally, the variable “horsepower” exhibits a high variability in the data. It is observed that the absolute frequency varies between approximately 2 and 10 for different horsepower values.</p>
</section>
<section id="correlation" class="level3">
<h3 class="anchored" data-anchor-id="correlation">Correlation</h3>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>corr_matrix <span class="op">=</span> df.corr()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>sns.heatmap(corr_matrix, square<span class="op">=</span><span class="va">True</span>, annot<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>ax)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-12-output-1.png" width="837" height="783"></p>
</div>
</div>
<p>In the correlation analysis, the following relationships stand out:</p>
<ul>
<li><p>The correlation between displacement and cylinders is 0.95. This strong positive correlation suggests that as engine displacement increases, the number of cylinders also increases. This makes sense, since larger engines tend to have more cylinders to generate more power.</p></li>
<li><p>The correlation between displacement and horsepower is 0.9. This positive correlation also indicates a strong relationship, meaning that as engine displacement increases, horsepower tends to increase as well. This is logical, as larger engines tend to have higher horsepower.</p></li>
<li><p>The correlation between horsepower and weight is 0.86. This positive correlation suggests that as engine horsepower increases, vehicle weight tends to increase as well. This could be attributed to the fact that more powerful vehicles often require heavier components to support that additional power.</p></li>
<li><p>The correlation between horsepower and cylinders is 0.84. This positive correlation indicates that as engine horsepower increases, the number of cylinders tends to increase as well. This is consistent with the correlation observed between displacement and cylinders, since both attributes are related to engine size and power (to take into account for a multiple linear regression model).</p></li>
<li><p>The correlation between mpg (miles per gallon) and weight is -0.83. This strong negative correlation indicates that as vehicle weight increases, fuel economy in terms of miles per gallon decreases. This is understandable, as heavier vehicles generally require more energy to move and therefore have higher fuel consumption.</p></li>
<li><p>The correlation between mpg and displacement is -0.81. This negative correlation suggests that as engine displacement increases, fuel economy in terms of miles per gallon decreases. This makes sense, as larger and more powerful engines tend to consume more fuel.</p></li>
</ul>
<p>Based on this, the following models are proposed</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Support functions</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_regression_model(model, x_label, y_label):</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> df[x_label]</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> df[y_label]</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    plt.scatter(x, y)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, model.predict(), color<span class="op">=</span><span class="st">'red'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(x_label)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(y_label)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f'Simple Linear Regression: </span><span class="sc">{</span>x_label<span class="sc">}</span><span class="ss"> vs </span><span class="sc">{</span>y_label<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> shapiro</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.diagnostic <span class="im">import</span> het_breuschpagan</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> checkModelAssumptions(model):</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    residuos <span class="op">=</span> model.resid</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    fig, axs <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">2</span>, ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    <span class="co">#QQ plot</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    sm.qqplot(residuos, line<span class="op">=</span><span class="st">'45'</span>, ax<span class="op">=</span>axs[<span class="dv">0</span>,<span class="dv">0</span>])</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">0</span>,<span class="dv">0</span>].set_title(<span class="st">'Residuals Q-Q plot'</span>)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Residuals Histogram</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">0</span>,<span class="dv">1</span>].hist(residuos, bins<span class="op">=</span><span class="dv">30</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">0</span>,<span class="dv">1</span>].set_xlabel(<span class="st">'Residuos'</span>)</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">0</span>,<span class="dv">1</span>].set_ylabel(<span class="st">'Frecuencia'</span>)</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">0</span>,<span class="dv">1</span>].set_title(<span class="st">'Residuals Histogram'</span>)</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Reiduals Boxplot</span></span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">1</span>,<span class="dv">0</span>].boxplot(residuos)</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">1</span>,<span class="dv">0</span>].set_ylabel(<span class="st">'Residuals'</span>)</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">1</span>,<span class="dv">0</span>].set_title(<span class="st">'Residuals Boxplot'</span>)</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Residuals</span></span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">1</span>,<span class="dv">1</span>].scatter(model.fittedvalues, model.resid_pearson)</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">1</span>,<span class="dv">1</span>].plot([<span class="bu">min</span>(model.fittedvalues), <span class="bu">max</span>(model.fittedvalues)], [<span class="dv">0</span>, <span class="dv">0</span>], <span class="st">'k--'</span>, lw<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">1</span>,<span class="dv">1</span>].set_xlabel(<span class="st">'Fitted Values'</span>)</span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">1</span>,<span class="dv">1</span>].set_ylabel(<span class="st">'Residuals'</span>)</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>    axs[<span class="dv">1</span>,<span class="dv">1</span>].set_title(<span class="st">' Standarized Residuals'</span>)</span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Normality test</span></span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'================= Normality test ================='</span>)</span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a>    stat, p <span class="op">=</span> shapiro(residuos)</span>
<span id="cb16-43"><a href="#cb16-43" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Estadística de prueba:'</span>, stat)</span>
<span id="cb16-44"><a href="#cb16-44" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Valor p:'</span>, p)</span>
<span id="cb16-45"><a href="#cb16-45" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> p <span class="op">&lt;=</span> <span class="fl">0.05</span>: <span class="bu">print</span>(<span class="st">"Se rechaza H0"</span>)</span>
<span id="cb16-46"><a href="#cb16-46" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>: <span class="bu">print</span>(<span class="st">"No se rechaza H0"</span>)</span>
<span id="cb16-47"><a href="#cb16-47" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Homoscedasticity test</span></span>
<span id="cb16-48"><a href="#cb16-48" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'================= Homoscedasticity test ================='</span>)</span>
<span id="cb16-49"><a href="#cb16-49" aria-hidden="true" tabindex="-1"></a>    lm, lm_pvalue, fvalue, f_pvalue <span class="op">=</span> het_breuschpagan(residuos, model.model.exog)</span>
<span id="cb16-50"><a href="#cb16-50" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Lagrange multiplier statistic:'</span>, lm)</span>
<span id="cb16-51"><a href="#cb16-51" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'p-value'</span>, lm_pvalue)</span>
<span id="cb16-52"><a href="#cb16-52" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'F value:'</span>, fvalue)</span>
<span id="cb16-53"><a href="#cb16-53" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'F p-value'</span>, f_pvalue)</span>
<span id="cb16-54"><a href="#cb16-54" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> lm_pvalue <span class="op">&lt;=</span> <span class="fl">0.05</span>: <span class="bu">print</span>(<span class="st">"Se rechaza H0"</span>)</span>
<span id="cb16-55"><a href="#cb16-55" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>: <span class="bu">print</span>(<span class="st">"No se rechaza H0"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">Simple Linear Regression</h2>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model for "displacement" and "cylinders"</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'cylinders ~ displacement'</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model1.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:              cylinders   R-squared:                       0.904
Model:                            OLS   Adj. R-squared:                  0.904
Method:                 Least Squares   F-statistic:                     3675.
Date:                Sun, 04 Jun 2023   Prob (F-statistic):          1.30e-200
Time:                        02:36:43   Log-Likelihood:                -305.62
No. Observations:                 392   AIC:                             615.2
Df Residuals:                     390   BIC:                             623.2
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        2.4587      0.056     43.571      0.000       2.348       2.570
displacement     0.0155      0.000     60.624      0.000       0.015       0.016
==============================================================================
Omnibus:                        5.983   Durbin-Watson:                   1.475
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                6.236
Skew:                           0.216   Prob(JB):                       0.0442
Kurtosis:                       3.441   Cond. No.                         466.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>The coefficient of determination (R-squared) is 0.904, which means that approximately 90.4% of the variability in the number of cylinders can be explained by engine displacement. The adjusted R-squared is also 0.904, indicating that the model is not over-fit and that the inclusion of the displacement variable is significant. The estimated coefficients of the model are 2.4587 for the intercept and 0.0155 for the displacement coefficient. Both coefficients are statistically significant (p-values close to zero). Therefore, on average, it is expected that for each unit increase in engine displacement, the number of cylinders will increase by approximately 0.0155. The 95% confidence intervals for the coefficients indicate that we can be 95% confident that the true values of the coefficients are within the intervals [2.348, 2.570] for the intercept and [0.015, 0.016] for “displacement”</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>plot_regression_model(model1, <span class="st">'displacement'</span>, <span class="st">'cylinders'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-15-output-1.png" width="576" height="442"></p>
</div>
</div>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>checkModelAssumptions(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-16-output-1.png" width="1142" height="566"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Normality test =================
Estadística de prueba: 0.977631151676178
Valor p: 9.41832968237577e-06
Se rechaza H0
================= Homoscedasticity test =================
Lagrange multiplier statistic: 53.203843897950094
p-value 3.0066986139946224e-13
F value: 61.24478907591415
F p-value 4.788834424237686e-14
Se rechaza H0</code></pre>
</div>
</div>
<p>Model 1 shows violations in the assumptions of normality and homoscedasticity for the residuals. In addition, the residuals follow a non-random pattern. This suggests that the model does not fully capture the structure of the data.</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model for "displacement" and "horsepower"</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'horsepower ~ displacement'</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model2.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:             horsepower   R-squared:                       0.805
Model:                            OLS   Adj. R-squared:                  0.805
Method:                 Least Squares   F-statistic:                     1611.
Date:                Sun, 04 Jun 2023   Prob (F-statistic):          1.51e-140
Time:                        02:36:45   Log-Likelihood:                -1666.2
No. Observations:                 392   AIC:                             3336.
Df Residuals:                     390   BIC:                             3344.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       40.3061      1.815     22.206      0.000      36.738      43.875
displacement     0.3300      0.008     40.134      0.000       0.314       0.346
==============================================================================
Omnibus:                       26.744   Durbin-Watson:                   1.168
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               46.621
Skew:                           0.436   Prob(JB):                     7.52e-11
Kurtosis:                       4.447   Cond. No.                         466.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>The analysis of the second regression model shows a strong relationship between engine displacement and horsepower. The coefficient of determination (R-squared) is 0.805, indicating that approximately 80.5% of the variability in horsepower can be explained by engine displacement. The adjusted R-squared is also 0.805, indicating that the model is not over-fit and that the inclusion of the displacement variable is significant.</p>
<p>The estimated coefficients of the model are 40.3061 for the intercept and 0.3300 for the displacement coefficient. Both coefficients are statistically significant (p-values close to zero). This means that, on average, for each unit increase in engine displacement, the horsepower is expected to increase by approximately 0.3300.</p>
<p>The 95% confidence intervals for the coefficients indicate that we can be 95% confident that the true values of the coefficients are within the intervals [36.738, 43.875] for the intercept and [0.314, 0.346] for “displacement”.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>plot_regression_model(model2, <span class="st">'displacement'</span>, <span class="st">'horsepower'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-18-output-1.png" width="593" height="442"></p>
</div>
</div>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>checkModelAssumptions(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-19-output-1.png" width="1142" height="566"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Normality test =================
Estadística de prueba: 0.9744998216629028
Valor p: 2.2193339646037202e-06
Se rechaza H0
================= Homoscedasticity test =================
Lagrange multiplier statistic: 19.333635803734893
p-value 1.0975580432936778e-05
F value: 20.232891100109065
F p-value 9.058404464197071e-06
Se rechaza H0</code></pre>
</div>
</div>
<p>For model 2, violations of the assumptions of normality and homoscedasticity of the residuals are also observed. The normality analysis of the residuals shows that they do not follow a normal distribution, as evidenced by the p-value significantly less than 0.05 and in the QQ plot. This indicates that the model residuals do not conform to the normality assumption, which may affect the validity of statistical inferences.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model for "horsepower" and "cylinders"</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>model3 <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'cylinders ~ horsepower'</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model3.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:              cylinders   R-squared:                       0.711
Model:                            OLS   Adj. R-squared:                  0.710
Method:                 Least Squares   F-statistic:                     957.7
Date:                Sun, 04 Jun 2023   Prob (F-statistic):          4.63e-107
Time:                        02:36:47   Log-Likelihood:                -522.02
No. Observations:                 392   AIC:                             1048.
Df Residuals:                     390   BIC:                             1056.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.5692      0.134     11.677      0.000       1.305       1.833
horsepower     0.0374      0.001     30.947      0.000       0.035       0.040
==============================================================================
Omnibus:                        0.089   Durbin-Watson:                   1.323
Prob(Omnibus):                  0.957   Jarque-Bera (JB):                0.178
Skew:                           0.024   Prob(JB):                        0.915
Kurtosis:                       2.907   Cond. No.                         322.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>The analysis of the third regression model reveals a significant relationship between horsepower and the number of cylinders. The coefficient of determination (R-squared) is 0.711, indicating that approximately 71.1% of the variability in the number of cylinders can be explained by horsepower. The adjusted R-squared is also 0.710, suggesting that the model is not over-fit and that the inclusion of the horsepower variable is significant.</p>
<p>The estimated coefficients of the model are 1.5692 for the intercept and 0.0374 for the horsepower coefficient. Both coefficients are statistically significant, as their p-values are close to zero. This implies that, on average, for each unit increase in horsepower, the number of cylinders is expected to increase by approximately 0.0374.</p>
<p>The 95% confidence intervals for the coefficients are [1.305, 1.833] for the intercept and [0.035, 0.040] for “horsepower.” This suggests that we can be 95% confident that the true values of the coefficients fall within these intervals.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>plot_regression_model(model3, <span class="st">'horsepower'</span>, <span class="st">'cylinders'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-21-output-1.png" width="585" height="442"></p>
</div>
</div>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>checkModelAssumptions(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-22-output-1.png" width="1142" height="566"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Normality test =================
Estadística de prueba: 0.9940255284309387
Valor p: 0.12716612219810486
No se rechaza H0
================= Homoscedasticity test =================
Lagrange multiplier statistic: 27.9577926963373
p-value 1.239906178721913e-07
F value: 29.951304911401273
F p-value 7.942070789332036e-08
Se rechaza H0</code></pre>
</div>
</div>
<p>Although the residuals of model 3 approximate a normal distribution, the presence of heteroscedasticity and the non-random pattern in the residuals suggest that there are aspects of the model that can be improved.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model for "mpg" and "weight"</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>model4 <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'weight ~ mpg'</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model4.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 weight   R-squared:                       0.693
Model:                            OLS   Adj. R-squared:                  0.692
Method:                 Least Squares   F-statistic:                     878.8
Date:                Sun, 04 Jun 2023   Prob (F-statistic):          6.02e-102
Time:                        02:36:48   Log-Likelihood:                -2968.4
No. Observations:                 392   AIC:                             5941.
Df Residuals:                     390   BIC:                             5949.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   5101.1136     75.487     67.576      0.000    4952.701    5249.526
mpg          -90.5714      3.055    -29.645      0.000     -96.578     -84.565
==============================================================================
Omnibus:                        4.278   Durbin-Watson:                   0.870
Prob(Omnibus):                  0.118   Jarque-Bera (JB):                4.151
Skew:                           0.209   Prob(JB):                        0.125
Kurtosis:                       2.718   Cond. No.                         78.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>The fourth regression model examines the relationship between the weight of the vehicle and its miles per gallon (mpg). The analysis reveals a significant negative relationship between these variables. The coefficient of determination (R-squared) is 0.693, indicating that approximately 69.3% of the variability in vehicle weight can be explained by mpg. The adjusted R-squared is also 0.692, suggesting that the inclusion of the mpg variable is significant and the model is not over-fit.</p>
<p>The estimated coefficients of the model are 5101.1136 for the intercept and -90.5714 for the mpg coefficient. Both coefficients are statistically significant, as their p-values are close to zero. This implies that, on average, for each unit increase in mpg, the weight of the vehicle is expected to decrease by approximately 90.5714 pounds.</p>
<p>The 95% confidence intervals for the coefficients are [4952.701, 5249.526] for the intercept and [-96.578, -84.565] for “mpg.” This indicates that we can be 95% confident that the true values of the coefficients fall within these intervals.</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>plot_regression_model(model4, <span class="st">'mpg'</span>, <span class="st">'weight'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-24-output-1.png" width="601" height="442"></p>
</div>
</div>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>checkModelAssumptions(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-25-output-1.png" width="1142" height="566"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Normality test =================
Estadística de prueba: 0.9943320155143738
Valor p: 0.15512245893478394
No se rechaza H0
================= Homoscedasticity test =================
Lagrange multiplier statistic: 0.08781997666224495
p-value 0.7669671160177225
F value: 0.08739149392151216
F p-value 0.7676772277112628
No se rechaza H0</code></pre>
</div>
</div>
<p>Model 4 meets the assumptions of normality and homoscedasticity in the residuals. However, the presence of a U-shaped pattern in the residuals indicates the need to consider a more complex model specification to adequately capture the nonlinear relationship between the variables.</p>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">Multiple Linear Regression</h2>
<p>Based on the correlations, it appears that displacement, cylinders, horsepower, and weight are all strongly correlated with each other and with the target variable, mpg (miles per gallon). These variables can be considered as potential predictors in a multiple linear regression model.</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(formula<span class="op">=</span><span class="st">'mpg ~ displacement + cylinders + horsepower + weight'</span>, data<span class="op">=</span>df).fit()</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.708
Model:                            OLS   Adj. R-squared:                  0.705
Method:                 Least Squares   F-statistic:                     234.2
Date:                Sun, 04 Jun 2023   Prob (F-statistic):          6.18e-102
Time:                        02:36:50   Log-Likelihood:                -1120.1
No. Observations:                 392   AIC:                             2250.
Df Residuals:                     387   BIC:                             2270.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       45.7568      1.520     30.102      0.000      42.768      48.745
displacement     0.0001      0.009      0.015      0.988      -0.018       0.018
cylinders       -0.3933      0.410     -0.960      0.338      -1.199       0.412
horsepower      -0.0428      0.013     -3.327      0.001      -0.068      -0.018
weight          -0.0053      0.001     -7.364      0.000      -0.007      -0.004
==============================================================================
Omnibus:                       37.596   Durbin-Watson:                   0.862
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               50.918
Skew:                           0.696   Prob(JB):                     8.77e-12
Kurtosis:                       4.085   Cond. No.                     2.23e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.23e+04. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<p>The model as a whole is statistically significant, with an F-value of 234.2 and a very low p-value (6.18e-102), indicating that at least one of the predictor variables has a significant effect on the target variable.</p>
<p>The coefficient of determination (R-squared) of the model is 0.708, which means that approximately 70.8% of the variability in the variable “mpg” can be explained by the predictor variables included in the model. The adjusted coefficient of determination (adjusted R-squared) is 0.705, which takes into account the number of predictor variables and penalizes the inclusion of irrelevant variables.</p>
<p>Examining the regression coefficients for each predictor variable, we note that the coefficient for “displacement” is close to zero (0.0001) and is not statistically significant (p &gt; 0.05). This suggests that there is no significant linear relationship between the variable “displacement” and the target variable “mpg”.</p>
<p>The coefficient for “cylinders” is -0.3933, but it is also not statistically significant (p &gt; 0.05). This indicates that the variable “cylinders” does not have a significant linear effect on the variable “mpg” when controlling for the other predictor variables.</p>
<p>On the other hand, the coefficient for “horsepower” is -0.0428 and is statistically significant (p &lt; 0.05). This suggests that, holding the other variables constant, a one unit increase in the horsepower variable is associated on average with a 0.0428 unit decrease in the mpg variable.</p>
<p>Finally, the coefficient for “weight” is -0.0053 and is also statistically significant (p &lt; 0.05). This indicates that, holding the other variables constant, a one unit increase in the “weight” variable is associated on average with a 0.0053 unit decrease in the “mpg” variable.</p>
<p>In summary, the multiple linear regression model suggests that the variables “displacement” and “cylinders” do not have a significant linear relationship with the variable “mpg”. However, the variables “horsepower” and “weight” do have a significant effect on the target variable, with higher “horsepower” and “weight” being associated with a decrease in “mpg”.</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>checkModelAssumptions(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-27-output-1.png" width="1142" height="566"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Normality test =================
Estadística de prueba: 0.9724681973457336
Valor p: 9.123047561843123e-07
Se rechaza H0
================= Homoscedasticity test =================
Lagrange multiplier statistic: 31.211241968341973
p-value 2.7721711596957605e-06
F value: 8.36968334853748
F p-value 1.7483109755393702e-06
Se rechaza H0</code></pre>
</div>
</div>
<p>The multiple linear regression model used to predict the variable “mpg” does not meet the assumptions of normality of the residuals and homoscedasticity. In addition, a higher clustering of the residuals is observed on the right side compared to the left side. This skewness in the distribution of the residuals may indicate an additional violation of the linearity assumption or may be related to the non-normality of the residuals.</p>
</section>
<section id="pca" class="level2">
<h2 class="anchored" data-anchor-id="pca">PCA</h2>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.decomposition <span class="im">import</span> PCA</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The variable 'name', which does not contribute anything to the model, is eliminated.</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The target variable is also eliminated</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>df_copy <span class="op">=</span> df.copy()</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>df_copy <span class="op">=</span> df_copy.drop([<span class="st">'name'</span>, <span class="st">'mpg'</span>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize variables. This will ensure that the variables contribute equally to the analysis.</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>data_scaled <span class="op">=</span> scaler.fit_transform(df_copy)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>pca <span class="op">=</span> PCA()</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>pca.fit(data_scaled)</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>X_pca <span class="op">=</span> pca.fit_transform(data_scaled)</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain variance explained by each component</span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>explained_variance <span class="op">=</span> pca.explained_variance_ratio_</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>plt.plot(np.cumsum(explained_variance))</span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'number of components'</span>)</span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'cumulative explained variance'</span>)</span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-28-output-1.png" width="597" height="422"></p>
</div>
</div>
<p>The first 3 components are chosen since they already explain 90% of the variance of the data.</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>X_pca_selected <span class="op">=</span> sm.add_constant(X_pca[:, :<span class="dv">3</span>])</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'mpg'</span>]</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>model_pca <span class="op">=</span> sm.OLS(y, X_pca_selected).fit()</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_pca.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.788
Model:                            OLS   Adj. R-squared:                  0.787
Method:                 Least Squares   F-statistic:                     481.5
Date:                Sun, 04 Jun 2023   Prob (F-statistic):          2.25e-130
Time:                        02:36:52   Log-Likelihood:                -1056.9
No. Observations:                 392   AIC:                             2122.
Df Residuals:                     388   BIC:                             2138.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         23.4459      0.182    128.754      0.000      23.088      23.804
x1            -3.0859      0.085    -36.393      0.000      -3.253      -2.919
x2            -0.3901      0.188     -2.077      0.038      -0.759      -0.021
x3            -2.2701      0.211    -10.754      0.000      -2.685      -1.855
==============================================================================
Omnibus:                       30.837   Durbin-Watson:                   1.296
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               56.646
Skew:                           0.479   Prob(JB):                     5.00e-13
Kurtosis:                       4.597   Cond. No.                         2.49
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>The multiple linear regression model using the three principal components shows a good fit to the data. The R-squared coefficient is 0.788, indicating that approximately 78.8% of the variability in the target variable (mpg) can be explained by the selected predictor variables. This suggests that the principal components capture a significant part of the information contained in the original variables.</p>
<p>When analyzing the estimated coefficients, it is observed that component 1 (x1) has a significant negative effect on the value of the target variable (mpg). This implies that as the value of component 1 increases, the value of mpg is expected to decrease. Similarly, component 2 (x2) also has a negative effect, although in a smaller magnitude. Component 3 (x3) shows an even greater impact on the target variable, also with a negative effect.</p>
<p>The statistical significance of the coefficients is confirmed by the associated p-values. All coefficients have p-values less than 0.05, indicating that they are statistically significant. This means that we can be confident in the relationship between the principal components and the target variable in the model.</p>
<p>In conclusion, the multiple linear regression model using the three principal components provides good explanatory power for the variability in the target variable (mpg).</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>checkModelAssumptions(model_pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="parcial3_files/figure-html/cell-30-output-1.png" width="1142" height="566"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Normality test =================
Estadística de prueba: 0.972704291343689
Valor p: 1.0097318181578885e-06
Se rechaza H0
================= Homoscedasticity test =================
Lagrange multiplier statistic: 25.070272841737527
p-value 1.4926830562085385e-05
F value: 8.836629235002121
F p-value 1.1147678707514367e-05
Se rechaza H0</code></pre>
</div>
</div>
<p>The analysis of the multiple linear regression model reveals some violations of the fundamental assumptions. First, it is observed that the residuals do not follow a normal distribution, which may affect the validity of the statistical inferences made. In addition, evidence of heteroscedasticity is found in the residuals, indicating that the variance of the errors is not constant. This may have implications for the precision of the estimated coefficients and the conclusions of the model. In addition, a higher clustering is observed on the right-hand side of the residuals, suggesting the presence of systematic patterns or nonlinearities that are not being captured by the model.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>